language: go

before_install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

install:
- go get -d -v -t ./...

script: PATH=$GOPATH/bin:$PATH ./bin/test

go:
- 1.7
- tip

matrix:
  allow_failures:
    - go: tip
